<!DOCTYPE html>
<html>
<head>
    <title>Minimal Grade Calculator</title>
</head>
<body>
    <h1>Grade Calculator</h1>
    
    <?php
        echo "<p>This text was generated by PHP!</p>";
        echo "<p>Today is: " . date('Year 2025-mounth 08/27-day Wednesday') . "</p>";
    ?>
    
    <p>This text is regular HTML.</p>
</body>
</html>